### ISSUE TITLE
docker install issue

### ISSUE THREAD

**Issue by saras224** [yfukasawa/LongQC#29] opened 2021-07-22 06:59 UTC
Hi @yfukasawa 
I am having trouble installing the docker image of LongQC, it is showing some error related to glibc version. 
error: 
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
                                                                                         
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.28=0
  - pysam -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.28

Is there any other other option than docker file to install LongQC? or is there a way I can fix this bug?

Thanks in Advance 
Saraswati Awasthi

**Comment by yfukasawa** [comment] 2021-07-25 14:58
Hi @saras224,

Thank you for having interest in our tool. Not the same, but looks similar to #22. Python 3.8 seems to be not compatible with pysam on conda.
Indeed, I could reproduce this error, and could you please the updated Docker file?
If that doesn't work for you, let me know.

Y.

**Comment by yfukasawa** [comment] 2021-09-12 11:08
let me close this thread, and feel free to reopen when needed.
Y.

**Closed by yfukasawa** 2021-09-12 11:08 UTC
